<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create</title>
    <script src="/test.js"></script>
    <link rel="stylesheet"
          href="//cdn.jsdelivr.net/gh/highlightjs/cdn-release@10.2.1/build/styles/default.min.css">
    <script src="//cdn.jsdelivr.net/gh/highlightjs/cdn-release@10.2.1/build/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
</head>
<body>
<textarea id="code_snippet">// write your code here </textarea>
<input id="time_restriction" type="text"/>Time Restriction
<input id="views_restriction" type="text"/>View Restriction
<button id="send_snippet" type="submit" onclick="send()">Submit</button>
</body>
</html>